"""Тексты сайта FIRST LOOK в структуре Models 1 (models1.co.uk): RU / EN.
Модели, услуги, документы — в data.py. Здесь — навигация, разделы и подписи."""

# Дополнительные параметры моделей (для панели при наведении и страницы модели)
HAIR = {
    "elena-voss": ("платиновый блонд", "platinum blonde"), "mika-sorensen": ("пепельный блонд", "ash blonde"),
    "talia-renard": ("тёмно-каштановые", "dark brown"), "noor-delacroix": ("тёмно-каштановые", "dark brown"),
    "ines-kovac": ("чёрные", "black"), "saskia-lund": ("медно-рыжие", "copper red"),
    "priya-anand": ("медовый блонд", "honey blonde"), "amara-solheim": ("тёмно-русые", "dark blonde"),
    "theo-marchetti": ("тёмно-каштановые", "dark brown"), "kian-ashford": ("чёрные", "black"),
    "rasmus-voight": ("пепельный блонд", "ash blond"), "julien-marceau": ("тёмно-каштановые", "dark brown"),
    "dario-esposito": ("чёрные", "black"), "emil-vantongeren": ("чёрные", "black"),
    "noah-kessler": ("русые", "dark blond"), "felix-aurelio": ("светло-русые", "light brown"),
}
EYES = {
    "elena-voss": ("голубые", "blue"), "mika-sorensen": ("серые", "grey"), "talia-renard": ("серо-зелёные", "grey-green"),
    "noor-delacroix": ("зелёно-карие", "hazel"), "ines-kovac": ("зелёные", "green"), "saskia-lund": ("карие", "amber"),
    "priya-anand": ("серо-зелёные", "grey-green"), "amara-solheim": ("серо-голубые", "grey-blue"),
    "theo-marchetti": ("карие", "brown"), "kian-ashford": ("карие", "brown"), "rasmus-voight": ("голубые", "blue"),
    "julien-marceau": ("серо-зелёные", "grey-green"), "dario-esposito": ("карие", "brown"), "emil-vantongeren": ("карие", "brown"),
    "noah-kessler": ("зелёные", "green"), "felix-aurelio": ("серые", "grey"),
}

C = {
    "ru": {
        "brand": "first look",
        "nav": [("women", "женщины"), ("men", "мужчины"), ("services", "услуги"),
                ("about", "агентство"), ("apply", "заявка"), ("contact", "контакты")],
        "home": "главная",
        "board": {"women": "женщины", "men": "мужчины"},
        "cats": [("all", "все"), ("editorial", "эдиториал"), ("ecommerce", "маркетплейсы"), ("beauty", "бьюти")],
        "search": "поиск", "search_ph": "имя модели", "search_none": "никого не нашли",
        "fav": "избранное", "fav_add": "в избранное", "fav_remove": "убрать из избранного",
        "fav_empty": "здесь пока пусто. нажмите ♡ на фото модели, чтобы сохранить её.",
        "fav_h": "избранное", "fav_send": "отправить подборку",
        "menu": "меню", "close": "закрыть", "grid": "все модели",
        "st": {"height": "рост", "age": "возраст", "look": "внешность", "hair": "волосы", "eyes": "глаза", "license": "аренда"},
        "years": "лет", "cm": "см",
        "rent": "арендовать модель", "shoot": "снять в ии-фотосессии",
        "lic_v": "от 25 000 ₽ / мес",
        "services_h": "услуги", "services_from": "от",
        "video_h": "видео", "video_items": [
            ("first-look-film", "одно лицо. без ограничений", "фильм агентства · 21 с"),
            ("clip-casting", "без кастинга", "elena · 5 с"),
            ("clip-travel", "без поездок", "saskia · 7 с"),
            ("clip-shoot", "без съёмки", "kian · 7 с"),
        ],
        "about_tabs": [("agency", "агентство"), ("process", "как работаем"), ("faq", "вопросы")],
        "about_h": "агентство",
        "about_sections": [
            ("цифровые лица для настоящих кампаний", "Мы создаём ИИ-моделей и работаем с ними как с настоящими: у каждой постоянное лицо, а съёмка обходится без кастинга, поездок и аренды студии."),
            ("одно лицо — без ограничений", "Возьмите модель из каталога в аренду или пришлите нам одежду — готовую съёмку получите через 48 часов. Модель можно сделать эксклюзивной: тогда она будет только у вашего бренда."),
            ("мода, бьюти и маркетплейсы", "Мы снимаем каталоги, кампании и контент для соцсетей. Каждая модель появляется только в кадре — и только в том, который нужен вашему бренду."),
        ],
        "process_h": "от вещи до кампании за 48 часов",
        "prices_h": "цены",
        "apply_h": "заявка",
        "apply_sub": "как прислать вещи",
        "apply_list": [
            "Пришлите три фото каждой вещи — как в примерах.",
            "Подойдут фото на телефон: раскладкой на ровном полу, на манекене или на вешалке.",
            "Снимайте при ярком дневном свете, без фильтров и обработки.",
            "Нужны фото вещи спереди и сзади, плюс крупный план ткани или принта.",
            "Добавьте референсы: настроение, локации, модели из каталога, которые вам нравятся.",
        ],
        "apply_scroll": "листайте к заявке",
        "apply_examples": ["раскладка", "ткань", "результат"],
        "form_h": "оставить заявку",
        "need": "что нужно", "need_opts": [("license", "аренда модели"), ("photoshoot", "фотосессия"), ("exclusive", "эксклюзивное лицо")],
        "f_name": "имя", "f_email": "email", "f_brand": "бренд / магазин", "f_task": "коротко о задаче", "f_model": "модель",
        "f_send": "отправить заявку", "f_note": "Нажимая кнопку, вы соглашаетесь с ", "f_note_link": "политикой конфиденциальности",
        "f_err_email": "проверьте email", "f_err_name": "как к вам обращаться?",
        "contact_h": "контакты",
        "address": ["Москва", "онлайн-агентство"],
        "contact_cols": [("заявки", "hello@firstlook.ai"), ("аренда моделей", "models@firstlook.ai"),
                         ("ии-фотосессии", "shoot@firstlook.ai"), ("пресса", "press@firstlook.ai")],
        "tg": "@firstlook_agency",
        "legal": "© 2026 FIRST LOOK. ВСЕ ПРАВА ЗАЩИЩЕНЫ.",
        "ai_note": "ВСЕ МОДЕЛИ СОЗДАНЫ ИСКУССТВЕННЫМ ИНТЕЛЛЕКТОМ",
        "thanks_h": "заявка отправлена", "thanks_p": "Спасибо! Ответим в течение часа в рабочее время и пришлём подборку моделей под ваш бриф.",
        "nf_h": "страница не найдена", "nf_p": "Похоже, ссылка устарела.",
        "to_home": "на главную", "to_women": "женщины", "to_men": "мужчины",
        "skip": "К содержимому",
    },
    "en": {
        "brand": "first look",
        "nav": [("women", "women"), ("men", "men"), ("services", "services"),
                ("about", "about"), ("apply", "book"), ("contact", "contact")],
        "home": "home",
        "board": {"women": "women", "men": "men"},
        "cats": [("all", "all"), ("editorial", "editorial"), ("ecommerce", "e-commerce"), ("beauty", "beauty")],
        "search": "search", "search_ph": "model name", "search_none": "no one found",
        "fav": "favourites", "fav_add": "add to favourites", "fav_remove": "remove from favourites",
        "fav_empty": "nothing here yet. tap ♡ on a model's photo to save her.",
        "fav_h": "favourites", "fav_send": "send this selection",
        "menu": "menu", "close": "close", "grid": "all models",
        "st": {"height": "height", "age": "age", "look": "look", "hair": "hair", "eyes": "eyes", "license": "license"},
        "years": "", "cm": "cm",
        "rent": "license this model", "shoot": "use in an ai photoshoot",
        "lic_v": "from $290 / mo",
        "services_h": "services", "services_from": "from",
        "video_h": "video", "video_items": [
            ("first-look-film", "one face. no limits", "agency film · 21 s"),
            ("clip-casting", "no casting", "elena · 5 s"),
            ("clip-travel", "no travel", "saskia · 7 s"),
            ("clip-shoot", "no photoshoot", "kian · 7 s"),
        ],
        "about_tabs": [("agency", "agency"), ("process", "how it works"), ("faq", "faq's")],
        "about_h": "about",
        "about_sections": [
            ("digital faces for real campaigns", "We create and represent AI-generated models — consistent faces you can book like real talent, without casting, travel or studio days."),
            ("one face — no limits", "License a model from the roster, or send us your garments and receive a finished shoot in 48 hours. A model can become exclusive — then she belongs to your brand only."),
            ("fashion, beauty & e-commerce", "We shoot catalogs, campaigns and social content. Every model exists only in the frame — and only in the frame your brand needs."),
        ],
        "process_h": "from garment to campaign in 48 hours",
        "prices_h": "pricing",
        "apply_h": "book",
        "apply_sub": "how to send your garments",
        "apply_list": [
            "Send us three photos of each item — similar to the examples.",
            "Phone photos are fine: flat-lay on a plain floor, on a mannequin or on a hanger.",
            "Shoot in bright, natural light, with no filters or retouching.",
            "We need the front and the back, plus a close-up of the fabric or print.",
            "Add references: mood, locations, models from the roster you like.",
        ],
        "apply_scroll": "scroll to book",
        "apply_examples": ["flat-lay", "fabric", "result"],
        "form_h": "send a request",
        "need": "what do you need", "need_opts": [("license", "model license"), ("photoshoot", "photoshoot"), ("exclusive", "exclusive face")],
        "f_name": "name", "f_email": "email", "f_brand": "brand / store", "f_task": "tell us about the project", "f_model": "model",
        "f_send": "send request", "f_note": "By clicking the button you agree to the ", "f_note_link": "privacy policy",
        "f_err_email": "please check your email", "f_err_name": "how should we address you?",
        "contact_h": "contact",
        "address": ["Moscow", "online agency"],
        "contact_cols": [("requests", "hello@firstlook.ai"), ("model licensing", "models@firstlook.ai"),
                         ("ai photoshoots", "shoot@firstlook.ai"), ("press", "press@firstlook.ai")],
        "tg": "@firstlook_agency",
        "legal": "© 2026 FIRST LOOK. ALL RIGHTS RESERVED.",
        "ai_note": "ALL MODELS ARE AI-GENERATED",
        "thanks_h": "request sent", "thanks_p": "Thank you! We'll reply within an hour during business hours and send a selection of models for your brief.",
        "nf_h": "page not found", "nf_p": "The link may be outdated.",
        "to_home": "home", "to_women": "women", "to_men": "men",
        "skip": "Skip to content",
    },
}
