"""Контент сайта FIRST LOOK на двух языках. Правится здесь, затем `python src/build.py`."""

# ── Модели ───────────────────────────────────────────────────────────────
# cats: women / men + editorial / ecommerce / beauty
MODELS = [
    ("elena-voss", "Elena Voss", "women", ["editorial", "beauty"], ("Скандинавский тип", "Scandinavian"), 21, 178),
    ("mika-sorensen", "Mika Sorensen", "women", ["ecommerce"], ("Скандинавский тип", "Nordic"), 26, 176),
    ("talia-renard", "Talia Renard", "women", ["beauty", "editorial"], ("Европейский тип", "European"), 23, 175),
    ("noor-delacroix", "Noor Delacroix", "women", ["editorial"], ("Французский тип", "French"), 23, 174),
    ("ines-kovac", "Ines Kovac", "women", ["ecommerce", "beauty"], ("Средиземноморский тип", "Mediterranean"), 24, 177),
    ("saskia-lund", "Saskia Lund", "women", ["editorial"], ("Рыжая, голландский тип", "Redhead, Dutch"), 24, 179),
    ("priya-anand", "Priya Anand", "women", ["beauty"], ("Калифорнийский тип", "Californian"), 22, 173),
    ("amara-solheim", "Amara Solheim", "women", ["ecommerce", "editorial"], ("Славянский тип", "Slavic"), 20, 178),
    ("theo-marchetti", "Theo Marchetti", "men", ["ecommerce"], ("Итальянский тип", "Italian"), 27, 186),
    ("kian-ashford", "Kian Ashford", "men", ["editorial"], ("Афроамериканский тип", "African-American"), 26, 189),
    ("rasmus-voight", "Rasmus Voight", "men", ["editorial", "ecommerce"], ("Скандинавский тип", "Scandinavian"), 25, 191),
    ("julien-marceau", "Julien Marceau", "men", ["ecommerce"], ("Французский тип", "French"), 24, 185),
    ("dario-esposito", "Dario Esposito", "men", ["ecommerce"], ("Средиземноморский тип", "Mediterranean"), 31, 184),
    ("emil-vantongeren", "Emil Vantongeren", "men", ["editorial"], ("Южноевропейский тип", "Southern European"), 27, 187),
    ("noah-kessler", "Noah Kessler", "men", ["ecommerce", "editorial"], ("Американский тип", "American"), 29, 188),
    ("felix-aurelio", "Felix Aurelio", "men", ["editorial"], ("Славянский тип", "Slavic"), 24, 187),
]

CAT = {
    "ru": {"all": "Все", "women": "Женщины", "men": "Мужчины", "editorial": "Эдиториал", "ecommerce": "Маркетплейсы", "beauty": "Бьюти"},
    "en": {"all": "All", "women": "Women", "men": "Men", "editorial": "Editorial", "ecommerce": "E-commerce", "beauty": "Beauty"},
}

# ── Общие строки ─────────────────────────────────────────────────────────
T = {
    "ru": {
        "lang": "ru", "other": "en", "other_label": "EN",
        "nav": [("models", "Модели"), ("photoshoot", "ИИ-фотосессия"), ("pricing", "Цены")],
        "book": "Забронировать",
        "menu": "Меню", "close": "Закрыть",
        "hero_sub": "Агентство ИИ-моделей — цифровые лица для моды, бьюти и маркетплейсов",
        "hero_cta1": "Смотреть моделей", "hero_cta2": "Заказать ИИ-фотосессию", "scroll": "Вниз",
        "sound_on": "Пауза",
        "intro_h": "Цифровые лица для настоящих кампаний",
        "intro_p": "Мы создаём ИИ-моделей и работаем с ними как с настоящими: у каждой постоянное лицо, а съёмка обходится без кастинга, поездок и аренды студии. Возьмите модель из каталога в аренду или пришлите нам одежду — готовую съёмку получите через 48 часов.",
        "services_eyebrow": "Услуги", "services_h": "Два способа работать с нашими моделями",
        "services_aside": "Арендуйте готовое лицо для регулярного контента или передайте нам коллекцию и получите готовую съёмку. В обоих случаях — с коммерческой лицензией.",
        "svc1_tag": "Каталог", "svc1_h": "Аренда модели",
        "svc1_p": "Выберите лицо из каталога и снимайте его как постоянную модель бренда — для каталога, соцсетей и рекламы.",
        "svc1_pts": ["16 ИИ-моделей на выбор — девушки и мужчины", "Любые позы, образы и локации на весь срок аренды", "Коммерческое использование: сайт, соцсети, маркетплейсы, печать"],
        "svc1_price": "от 25 000 ₽ / мес", "svc1_cta": "Смотреть моделей",
        "svc2_tag": "Чаще всего заказывают", "svc2_h": "ИИ-фотосессия",
        "svc2_p": "Пришлите фото одежды — раскладкой или на манекене. Мы «оденем» в неё модель из каталога и сдадим готовую съёмку.",
        "svc2_pts": ["20 отретушированных кадров в 4K", "Студия, улица или любая локация", "Готово за 48 часов, два круга правок"],
        "svc2_price": "от 39 000 ₽ / съёмка", "svc2_cta": "Заказать съёмку",
        "roster_h": "Каталог ИИ-моделей", "roster_count": "моделей", "all_models": "Весь каталог",
        "process_eyebrow": "ИИ-фотосессия", "process_h": "От вещи до готовой кампании за 48 часов",
        "process_aside": "Без студии, кастинга и пересылки образцов. Всё проходит онлайн — от вас нужны только фото товара.",
        "steps": [
            ("Пришлите одежду", "Фото раскладкой, на манекене или на вешалке — спереди и сзади. Добавьте референсы нужного настроения."),
            ("Выберите модель и локацию", "Подберите лица из каталога и обстановку: студия, улица, интерьер или своя локация."),
            ("Генерируем и ретушируем", "Генерируем образы, вручную доводим ткань, посадку и детали и попадаем в цвет товара."),
            ("Получите файлы", "20 итоговых кадров в 4K с коммерческой лицензией. Два круга правок включены."),
        ],
        "scene": {"front": "Перед", "back": "Спинка", "upload": "Загрузка фото", "chips": ["Студия", "Улица", "Интерьер"],
                  "picked": "Выбрано: Saskia · Студия", "st_up": "Ожидание", "st_act": "Генерация · 72%", "st_done": "Готово · 100%", "files": "20 файлов · 4K"},
        "pricing_eyebrow": "Цены", "pricing_h": "Тарифы",
        "pricing_aside": "Цены указаны для одного бренда, без НДС. Нужен большой объём для маркетплейса? Соберём индивидуальный тариф.",
        "popular": "Популярное",
        "plans": [
            ("photoshoot", "Фотосессия", "39 000 ₽", "/ съёмка", "Для новой коллекции или сезонного дропа.",
             ["1 ИИ-модель из каталога", "20 кадров в 4K", "До 2 локаций", "Готово за 48 часов", "Коммерческая лицензия на год"], "Заказать съёмку", False),
            ("license", "Аренда модели", "25 000 ₽", "/ мес", "Постоянное лицо бренда для каталога и соцсетей.",
             ["Любая модель из каталога", "До 60 кадров в месяц", "Одно и то же лицо во всех съёмках", "Сайт, соцсети и маркетплейсы", "Можно отменить в любой момент"], "Арендовать модель", True),
            ("exclusive", "Эксклюзивное лицо", "250 000 ₽", "разово", "Модель, созданная только для вашего бренда.",
             ["Уникальное лицо по вашему брифу", "Не появляется в общем каталоге", "Полный выкуп прав", "Печать, наружная реклама и ТВ", "Приоритет в работе"], "Обсудить проект", False),
        ],
        "faq_eyebrow": "Вопросы", "faq_h": "Частые вопросы",
        "faq": [
            ("Это настоящие люди?", "Нет. Все модели полностью созданы ИИ. Мы не используем лицо, тело или внешность реальных людей — поэтому не нужны модельные релизы и поездки, и не бывает споров о правах."),
            ("Лицо будет одинаковым во всех съёмках?", "Да. У каждой модели закреплённая внешность, так что одно лицо проходит через весь каталог, соцсети и рекламу."),
            ("Кому принадлежат фото?", "К каждому кадру прилагается коммерческая лицензия. С тарифом «Эксклюзивное лицо» модель и все права принадлежат вашему бренду."),
            ("Насколько точно выглядит одежда?", "Работаем по фото вашего товара и вручную доводим ткань, посадку, принты и мелкие детали, пока они не совпадут с оригиналом."),
            ("Видео тоже делаете?", "Да — короткие ролики на 5–10 секунд для соцсетей и карточек товара можно добавить к любому тарифу."),
        ],
        "req_eyebrow": "Заявка", "req_h": "Закажите модель или съёмку",
        "req_p": "Ответим в течение часа в рабочее время и пришлём подборку моделей под ваш бриф.",
        "need": "Что нужно", "need_opts": [("license", "Аренда модели"), ("photoshoot", "Фотосессия"), ("exclusive", "Эксклюзивное лицо")],
        "f_name": "Имя", "f_email": "Email", "f_brand": "Бренд / магазин", "f_task": "Коротко о задаче", "f_model": "Модель",
        "f_send": "Отправить заявку", "f_note": "Нажимая кнопку, вы соглашаетесь с ", "f_note_link": "политикой конфиденциальности",
        "f_err_email": "Проверьте email", "f_err_name": "Как к вам обращаться?",
        "agency": "Агентство", "about": "Агентство ИИ-моделей для моды, бьюти и маркетплейсов. Постоянные лица для ваших кампаний — без кастингов и студий.",
        "col_nav": "Навигация", "col_nav_items": [("models", "Модели"), ("photoshoot", "ИИ-фотосессия"), ("process", "Как мы работаем"), ("pricing", "Цены"), ("faq", "Вопросы")],
        "col_srv": "Услуги", "col_doc": "Документы",
        "copy": "© 2026 First Look. Все права защищены.", "ai_note": "Все модели созданы искусственным интеллектом",
        "legal_line": "ООО «Ферст Лук» · ИНН 0000000000 · ОГРН 0000000000000", "top": "Наверх",
        "contacts": "Контакты",
        # модель
        "m_look": "Внешность", "m_age": "Возраст", "m_height": "Рост", "m_license": "Аренда", "m_license_v": "от 25 000 ₽ / мес",
        "m_excl": "Эксклюзив", "m_excl_v": "Доступен", "m_years": "лет", "m_cm": "см",
        "m_rent": "Арендовать модель", "m_shoot": "Снять в ИИ-фотосессии", "m_back": "Все модели",
        "m_more": "Другие модели", "m_prev": "Предыдущая", "m_next": "Следующая",
        "m_portrait": "Портрет", "m_full": "Полный рост",
        "m_about": "{name} — ИИ-модель агентства First Look. Внешность закреплена: лицо остаётся одинаковым во всех съёмках, поэтому модель можно сделать постоянным лицом бренда.",
        "models_h": "Все модели", "models_p": "16 ИИ-моделей с закреплённой внешностью. Выберите лицо для своего бренда — фото в полный рост появляется при наведении.",
        "empty": "В этой категории пока нет моделей",
        "price_from": "Стоимость", "included": "Что входит", "order": "Оставить заявку", "how": "Как это работает",
        "thanks_h": "Заявка отправлена", "thanks_p": "Спасибо! Мы ответим в течение часа в рабочее время и пришлём подборку моделей под ваш бриф.",
        "home": "На главную", "to_models": "Смотреть моделей",
        "nf_h": "Страница не найдена", "nf_p": "Похоже, ссылка устарела. Вернитесь на главную или загляните в каталог.",
        "socials": [("Instagram", "#"), ("Telegram", "#"), ("TikTok", "#"), ("Pinterest", "#")],
        "email": "hello@firstlook.ai", "tg": "@firstlook_agency", "ig": "@firstlook.models",
    },
    "en": {
        "lang": "en", "other": "ru", "other_label": "RU",
        "nav": [("models", "Models"), ("photoshoot", "AI photoshoot"), ("pricing", "Pricing")],
        "book": "Book a model",
        "menu": "Menu", "close": "Close",
        "hero_sub": "AI model agency — digital faces for fashion, beauty & e-commerce",
        "hero_cta1": "Browse models", "hero_cta2": "Order AI photoshoot", "scroll": "Scroll",
        "sound_on": "Pause",
        "intro_h": "Digital faces built for real campaigns",
        "intro_p": "We create and represent AI-generated models — consistent faces you can book like real talent, without casting, travel or studio days. License a model from our roster, or send us your garments and receive a finished campaign in 48 hours.",
        "services_eyebrow": "Services", "services_h": "Two ways to work with our models",
        "services_aside": "Book a ready-made face for ongoing content, or hand us your collection and get a finished shoot back. Both come with a commercial license.",
        "svc1_tag": "Roster", "svc1_h": "License a model",
        "svc1_p": "Choose a face from our roster and use it as your brand's recurring model — in catalog, social and ads.",
        "svc1_pts": ["Pick from 16 AI models — women and men", "Unlimited poses, looks and scenes during the term", "Commercial use: web, social, marketplaces, print"],
        "svc1_price": "from $290 / month", "svc1_cta": "Browse models",
        "svc2_tag": "Most requested", "svc2_h": "AI photoshoot",
        "svc2_p": "Send flat-lay or mannequin photos of your garments. We dress a model from the roster in them and deliver a finished set.",
        "svc2_pts": ["20 retouched images in 4K per shoot", "Studio, street or location scenes", "Delivered in 48 hours, two rounds of edits"],
        "svc2_price": "from $450 / shoot", "svc2_cta": "Order a shoot",
        "roster_h": "The AI roster", "roster_count": "models", "all_models": "Full roster",
        "process_eyebrow": "AI photoshoot", "process_h": "From garment to campaign in 48 hours",
        "process_aside": "No studio, no casting, no shipping samples. Everything happens online — you only send photos of the product.",
        "steps": [
            ("Send your garments", "Flat-lay, mannequin or hanger photos — front and back. Add references for the mood you want."),
            ("Pick model & scene", "Choose faces from the roster and a setting: studio, street, interior or a custom location."),
            ("We generate & retouch", "Our team generates the looks, then fixes fabric, fit and details by hand and color-matches your product."),
            ("Receive your files", "20 final images in 4K with a commercial license. Two rounds of edits are included."),
        ],
        "scene": {"front": "Front", "back": "Back", "upload": "Photo upload", "chips": ["Studio", "Street", "Interior"],
                  "picked": "Selected: Saskia · Studio", "st_up": "Queued", "st_act": "Generating · 72%", "st_done": "Done · 100%", "files": "20 files · 4K"},
        "pricing_eyebrow": "Pricing", "pricing_h": "Pricing",
        "pricing_aside": "Prices are per brand, excluding VAT. Need volume for a marketplace catalog? We'll put together a custom plan.",
        "popular": "Most popular",
        "plans": [
            ("photoshoot", "Photoshoot", "$450", "/ shoot", "For a new collection or a seasonal drop.",
             ["1 AI model from the roster", "20 images in 4K", "Up to 2 scenes", "48-hour delivery", "1-year commercial license"], "Order a shoot", False),
            ("license", "Model license", "$290", "/ month", "Your go-to face for catalog and social.",
             ["Any model from the roster", "Up to 60 images per month", "Same identity across every shoot", "Web, social & marketplaces", "Cancel anytime"], "License a model", True),
            ("exclusive", "Exclusive face", "$2,900", "one-time", "A model created for your brand only.",
             ["Custom face designed to your brief", "Removed from the public roster", "Full buyout of rights", "Print, OOH & TV usage", "Priority production"], "Discuss a project", False),
        ],
        "faq_eyebrow": "FAQ", "faq_h": "Frequently asked questions",
        "faq": [
            ("Are the models real people?", "No. Every model is fully AI-generated. No real person's face, body or likeness is used — so there are no model releases, travel or usage disputes."),
            ("Will the face stay the same across shoots?", "Yes. Each model has a fixed identity, so one face carries through your catalog, social content and campaigns."),
            ("Who owns the images?", "Every delivered image comes with a commercial license. With Exclusive Face, the model and all rights belong to your brand."),
            ("How accurate is the clothing?", "We work from your product photos and retouch fabric, fit, prints and small details by hand until they match the real item."),
            ("Can you make video too?", "Yes — short 5–10 second clips for social and product pages are available as an add-on to any plan."),
        ],
        "req_eyebrow": "Request", "req_h": "Book a model or a shoot",
        "req_p": "We reply within an hour during business hours and send a selection of models for your brief.",
        "need": "What do you need", "need_opts": [("license", "Model license"), ("photoshoot", "Photoshoot"), ("exclusive", "Exclusive face")],
        "f_name": "Name", "f_email": "Email", "f_brand": "Brand / store", "f_task": "Tell us about the project", "f_model": "Model",
        "f_send": "Send request", "f_note": "By clicking the button you agree to the ", "f_note_link": "privacy policy",
        "f_err_email": "Please check your email", "f_err_name": "How should we address you?",
        "agency": "Agency", "about": "AI model agency for fashion, beauty and e-commerce. Consistent faces for your campaigns — no castings, no studios.",
        "col_nav": "Navigation", "col_nav_items": [("models", "Models"), ("photoshoot", "AI photoshoot"), ("process", "How it works"), ("pricing", "Pricing"), ("faq", "FAQ")],
        "col_srv": "Services", "col_doc": "Legal",
        "copy": "© 2026 First Look. All rights reserved.", "ai_note": "All models are AI-generated",
        "legal_line": "First Look LLC · Reg. no. 0000000000", "top": "Back to top",
        "contacts": "Contacts",
        "m_look": "Look", "m_age": "Age", "m_height": "Height", "m_license": "License", "m_license_v": "from $290 / mo",
        "m_excl": "Exclusive", "m_excl_v": "Available", "m_years": "", "m_cm": "cm",
        "m_rent": "License this model", "m_shoot": "Use in an AI photoshoot", "m_back": "All models",
        "m_more": "More models", "m_prev": "Previous", "m_next": "Next",
        "m_portrait": "Portrait", "m_full": "Full length",
        "m_about": "{name} is an AI model represented by First Look. The look is fixed — the face stays the same across every shoot, so the model can become your brand's recurring face.",
        "models_h": "All models", "models_p": "16 AI models with a fixed identity. Choose a face for your brand — the full-length shot appears on hover.",
        "empty": "No models in this category yet",
        "price_from": "Price", "included": "What's included", "order": "Send a request", "how": "How it works",
        "thanks_h": "Request sent", "thanks_p": "Thank you! We'll reply within an hour during business hours and send a selection of models for your brief.",
        "home": "Back to home", "to_models": "Browse models",
        "nf_h": "Page not found", "nf_p": "The link may be outdated. Go back home or browse the roster.",
        "socials": [("Instagram", "#"), ("Telegram", "#"), ("TikTok", "#"), ("Pinterest", "#")],
        "email": "hello@firstlook.ai", "tg": "@firstlook_agency", "ig": "@firstlook.models",
    },
}

# ── Услуги (отдельные страницы) ─────────────────────────────────────────
SERVICES = {
    "license": {
        "img": ["elena-voss-portrait", "theo-marchetti-full", "saskia-lund-portrait"],
        "ru": {"title": "Аренда модели", "eyebrow": "Услуга", "lead": "Постоянное лицо бренда без кастингов и контрактов. Выберите модель из каталога — и снимайте её столько, сколько нужно, в любых образах и локациях.",
               "price": "25 000 ₽", "per": "в месяц", "plan": "license",
               "incl": ["Любая модель из каталога", "До 60 кадров в месяц", "Одно и то же лицо во всех съёмках", "Сайт, соцсети, маркетплейсы и печать", "Можно сменить модель или отменить аренду в любой момент"],
               "how": [("Выберите модель", "Откройте каталог и выберите одно или несколько лиц под ваш бренд."), ("Пришлите товар", "Фото вещей и референсы — мы подготовим первые кадры за 48 часов."), ("Снимайте каждый месяц", "До 60 новых кадров ежемесячно, лицо всегда одинаковое.")]},
        "en": {"title": "Model license", "eyebrow": "Service", "lead": "A recurring brand face with no castings or contracts. Pick a model from the roster and shoot as much as you need — any looks, any scenes.",
               "price": "$290", "per": "per month", "plan": "license",
               "incl": ["Any model from the roster", "Up to 60 images per month", "Same identity across every shoot", "Web, social, marketplaces and print", "Switch models or cancel anytime"],
               "how": [("Pick a model", "Browse the roster and choose one or several faces for your brand."), ("Send your product", "Garment photos and references — first images in 48 hours."), ("Shoot every month", "Up to 60 new images monthly, always the same face.")]},
    },
    "photoshoot": {
        "img": ["saskia-lund-full", "priya-anand-full", "dario-esposito-full"],
        "ru": {"title": "ИИ-фотосессия", "eyebrow": "Услуга", "lead": "Готовая съёмка новой коллекции за 48 часов. Без студии, фотографа и пересылки образцов — от вас нужны только фото товара.",
               "price": "39 000 ₽", "per": "за съёмку", "plan": "photoshoot",
               "incl": ["1 ИИ-модель из каталога", "20 отретушированных кадров в 4K", "До 2 локаций: студия, улица или интерьер", "Готово за 48 часов, два круга правок", "Коммерческая лицензия на год"],
               "how": None},
        "en": {"title": "AI photoshoot", "eyebrow": "Service", "lead": "A finished shoot of your new collection in 48 hours. No studio, photographer or shipping samples — you only send product photos.",
               "price": "$450", "per": "per shoot", "plan": "photoshoot",
               "incl": ["1 AI model from the roster", "20 retouched images in 4K", "Up to 2 scenes: studio, street or interior", "Delivered in 48 hours, two rounds of edits", "1-year commercial license"],
               "how": None},
    },
    "exclusive": {
        "img": ["amara-solheim-portrait", "julien-marceau-full", "noor-delacroix-portrait"],
        "ru": {"title": "Эксклюзивное лицо", "eyebrow": "Услуга", "lead": "Модель, созданная только для вашего бренда. Мы разрабатываем внешность по брифу, убираем её из общего каталога и передаём вам все права.",
               "price": "250 000 ₽", "per": "разово", "plan": "exclusive",
               "incl": ["Уникальное лицо по вашему брифу", "3 варианта внешности на выбор", "Не появляется в общем каталоге", "Полный выкуп прав", "Печать, наружная реклама и ТВ", "Приоритет в работе"],
               "how": [("Бриф", "Обсуждаем аудиторию, характер бренда и референсы."), ("Кастинг", "Показываем 3 варианта лица, дорабатываем выбранный."), ("Передача прав", "Фиксируем внешность и передаём права вашему бренду.")]},
        "en": {"title": "Exclusive face", "eyebrow": "Service", "lead": "A model created for your brand only. We design the look to your brief, remove it from the public roster and transfer all rights to you.",
               "price": "$2,900", "per": "one-time", "plan": "exclusive",
               "incl": ["Custom face designed to your brief", "3 look options to choose from", "Removed from the public roster", "Full buyout of rights", "Print, OOH & TV usage", "Priority production"],
               "how": [("Brief", "We discuss your audience, brand character and references."), ("Casting", "We show 3 face options and refine the chosen one."), ("Rights transfer", "We lock the identity and transfer the rights to your brand.")]},
    },
    "video": {
        "img": ["kian-ashford-full", "elena-voss-full", "rasmus-voight-full"],
        "ru": {"title": "Видео для соцсетей", "eyebrow": "Услуга", "lead": "Короткие ролики на 5–10 секунд с нашими моделями: проход по подиуму, движение ткани, крупные планы для карточек товара и сторис.",
               "price": "от 9 000 ₽", "per": "за ролик", "plan": "photoshoot",
               "incl": ["Ролики 5–10 секунд в 1080p или 4K", "Вертикальный и горизонтальный формат", "Модель из каталога или ваше эксклюзивное лицо", "Можно добавить к любому тарифу", "Готово за 3 рабочих дня"],
               "how": [("Сценарий", "Выбираем движение, локацию и длительность."), ("Генерация", "Делаем ролик и проверяем, что одежда выглядит как оригинал."), ("Монтаж", "Отдаём файлы под сторис, рилс и карточки товара.")]},
        "en": {"title": "Social video", "eyebrow": "Service", "lead": "Short 5–10 second clips with our models: runway walks, fabric in motion and close-ups for product pages and stories.",
               "price": "from $120", "per": "per clip", "plan": "photoshoot",
               "incl": ["5–10 second clips in 1080p or 4K", "Vertical and horizontal formats", "A roster model or your exclusive face", "Can be added to any plan", "Ready in 3 business days"],
               "how": [("Script", "We choose the motion, scene and length."), ("Generation", "We produce the clip and check the garment matches the original."), ("Edit", "Files delivered for stories, reels and product pages.")]},
    },
}
SERVICE_ORDER = ["license", "photoshoot", "exclusive", "video"]

# ── Документы ────────────────────────────────────────────────────────────
DOCS = {
    "privacy": {"ru": ("Политика конфиденциальности", [
        ("Какие данные мы собираем", "Имя, email, название бренда и описание задачи, которые вы указываете в форме заявки. Мы не собираем платёжные данные на сайте."),
        ("Зачем они нужны", "Чтобы ответить на заявку, подобрать моделей и подготовить предложение. Мы не продаём и не передаём данные третьим лицам, кроме случаев, предусмотренных законом."),
        ("Сколько храним", "Данные заявки хранятся до завершения работы над проектом и затем удаляются по вашему запросу или через 3 года."),
        ("Ваши права", "Вы можете запросить копию своих данных, их исправление или удаление, написав на hello@firstlook.ai."),
        ("Cookies", "Сайт использует только технические cookies, необходимые для его работы. Аналитика подключается с вашего согласия.")]),
        "en": ("Privacy policy", [
        ("What we collect", "Your name, email, brand name and project description entered in the request form. We do not collect payment data on this site."),
        ("Why we need it", "To reply to your request, select models and prepare an offer. We do not sell or share your data with third parties except as required by law."),
        ("How long we keep it", "Request data is kept until the project is complete, then deleted on request or after 3 years."),
        ("Your rights", "You can request a copy, correction or deletion of your data by writing to hello@firstlook.ai."),
        ("Cookies", "The site only uses technical cookies required for it to work. Analytics is enabled only with your consent.")])},
    "terms": {"ru": ("Пользовательское соглашение", [
        ("Общие положения", "Соглашение регулирует использование сайта First Look. Пользуясь сайтом, вы принимаете его условия."),
        ("Материалы сайта", "Изображения моделей на сайте демонстрационные. Использовать их в коммерческих целях можно только по лицензии."),
        ("Заявки", "Заявка на сайте не является офертой. Условия работы фиксируются в договоре."),
        ("Ответственность", "Мы стараемся поддерживать информацию на сайте актуальной, но цены и состав услуг могут меняться.")]),
        "en": ("Terms of use", [
        ("General", "These terms govern the use of the First Look website. By using the site you accept them."),
        ("Site materials", "Model images on this site are for demonstration. Commercial use requires a license."),
        ("Requests", "A request on the site is not an offer. Terms of work are set out in a contract."),
        ("Liability", "We keep the information up to date, but prices and services may change.")])},
    "image-license": {"ru": ("Лицензия на изображения", [
        ("Что даёт лицензия", "Право использовать изображения в рекламе и продаже ваших товаров: на сайте, в соцсетях, на маркетплейсах и в печати."),
        ("Срок", "Для фотосессии — 1 год с возможностью продления. Для аренды — на весь срок подписки. Для эксклюзивного лица — бессрочно."),
        ("Ограничения", "Нельзя выдавать ИИ-моделей за реальных людей, использовать их в политической рекламе и в материалах, нарушающих закон."),
        ("Маркировка", "Мы рекомендуем помечать изображения как созданные ИИ там, где этого требуют правила площадок.")]),
        "en": ("Image license", [
        ("What it covers", "The right to use images to advertise and sell your products: on your website, social media, marketplaces and in print."),
        ("Term", "Photoshoot — 1 year, renewable. License — for the subscription term. Exclusive face — perpetual."),
        ("Restrictions", "AI models may not be presented as real people, used in political advertising or in unlawful content."),
        ("Labelling", "We recommend labelling images as AI-generated wherever platform rules require it.")])},
    "company": {"ru": ("Реквизиты", [
        ("Компания", "ООО «Ферст Лук» (наименование — заглушка, заменить на реальное)"),
        ("Регистрационные данные", "ИНН 0000000000 · КПП 000000000 · ОГРН 0000000000000"),
        ("Адрес", "Москва, адрес уточняется"),
        ("Контакты", "hello@firstlook.ai · Telegram @firstlook_agency")]),
        "en": ("Company details", [
        ("Company", "First Look LLC (placeholder name)"),
        ("Registration", "Reg. no. 0000000000"),
        ("Address", "To be confirmed"),
        ("Contacts", "hello@firstlook.ai · Telegram @firstlook_agency")])},
}
DOC_ORDER = ["privacy", "terms", "image-license", "company"]
